describe('Bookmark functionality', () => {
  beforeEach(() => {
    cy.intercept('GET', 'https://immense-falls-83363.herokuapp.com/api/v1/businesses?location=Denver&category=shopping', { fixture: 'sampleShoppingData.json' }).as('shopping results')
    cy.intercept('GET', 'https://immense-falls-83363.herokuapp.com/api/v1/businesses?location=Denver&category=food', { fixture: 'sampleFoodData.json' }).as('food results')
    cy.intercept('GET', 'https://immense-falls-83363.herokuapp.com/api/v1/businesses/dKf_zc_gvlQJRXXZNkUNng', { fixture: 'singleBiz1.json' }).as('single biz')
    cy.intercept('GET', 'https://immense-falls-83363.herokuapp.com/api/v1/businesses/B2i4QJY03Iqo7gxdCnJbiw', { fixture: 'singleBiz2.json' }).as('single biz')
    cy.intercept('GET', 'https://immense-falls-83363.herokuapp.com/api/v1/recommendations?business_id=dKf_zc_gvlQJRXXZNkUNng', { fixture: 'noResults.json' }).as('recommendations')
    cy.intercept('GET', 'https://immense-falls-83363.herokuapp.com/api/v1/recommendations?business_id=B2i4QJY03Iqo7gxdCnJbiw', { fixture: 'noResults.json' }).as('recommendations')
    cy.visit('http://localhost:3000')
      .get('form input').type('Denver')
      .get('.submit-button').click()
  })

  it('should let you bookmark pages', () => {
    cy.get('button').eq(2).click()
      .url('http://localhost:3000/shopping')
    cy.get('button')
      .should('contain', 'Bookmark').eq(7).click()
      .get('button')
      .should('contain', 'Un-Bookmark')
  })

  it('should let you view your bookmarks', () => {
    cy.get('button').eq(1).click()
      .url('http://localhost:3000/food')
    cy.get('div[id="5G2X2q9p7QFdm-LbyutltQ"] button:last').click()
      .get('button').eq(4).click()
    cy.url('http://localhost:3000/bookmarks')
      .get('.bookmarks-container')
      .get('.saved-businesses')
      .should('contain', 'Jelly')
  })

  it('should let you remove bookmarks in listings view', () => {
    cy.get('button').eq(2).click()
      .url('http://localhost:3000/shopping')
    cy.get('div[id="dKf_zc_gvlQJRXXZNkUNng"] button:last')
      .should('contain', 'Bookmark').click()
      .get('div[id="dKf_zc_gvlQJRXXZNkUNng"] button:last')
      .should('contain', 'Un-Bookmark').click()
      .get('div[id="dKf_zc_gvlQJRXXZNkUNng"] button:last')
      .should('contain', 'Bookmark')
  })

  it('should let you remove bookmarks in bookmarks view', () => {
    cy.get('button').eq(2).click()
      .url('http://localhost:3000/shopping')
    cy.get('div[id="dKf_zc_gvlQJRXXZNkUNng"] button:last')
      .should('contain', 'Bookmark').click()
      .get('button').eq(4).click()
    cy.url('http://localhost:3000/bookmarks')
      .get('.bookmarks-container')
      .should('contain', 'Stanley Marketplace')
      .get('button:last')
      .should('contain', 'Un-Bookmark').click()
      .get('.bookmarks-container')
      .should('not.contain', 'Stanley Marketplace')
  })
    
  it('should let you view a single business from the bookmarks page', () => {
    cy.get('button').eq(2).click()
      .url('http://localhost:3000/shopping')
      .get('div[id="dKf_zc_gvlQJRXXZNkUNng"] button:last').click()
      .get('button').eq(4).click()
      .url('http://localhost:3000/bookmarks')
      .get('div[id="dKf_zc_gvlQJRXXZNkUNng"] button:first').click()
    cy.url('http://localhost:3000/biz/B2i4QJY03Iqo7gxdCnJbiw')
      .get('h2')
      .should('contain', 'Stanley Marketplace')
  })
})