describe('Going back functionality', () => {
  beforeEach(() => {
    cy.intercept('GET', 'http://www.geoplugin.net/json.gp', { fixture: 'sampleGeoData.json' }).as('location data')
    cy.intercept('GET', 'https://immense-falls-83363.herokuapp.com/api/v1/businesses?location=Denver&category=shopping', { fixture: 'sampleShoppingData.json' }).as('shopping results')
    cy.intercept('GET', 'https://immense-falls-83363.herokuapp.com/api/v1/businesses?location=Denver&category=food', { fixture: 'sampleFoodData.json' }).as('food results')
    cy.intercept('GET', 'https://immense-falls-83363.herokuapp.com/api/v1/businesses/B2i4QJY03Iqo7gxdCnJbiw', { fixture: 'singleBiz2.json' }).as('single biz')
    cy.intercept('GET', 'https://immense-falls-83363.herokuapp.com/api/v1/businesses/dKf_zc_gvlQJRXXZNkUNng', { fixture: 'singleBiz1.json' }).as('single biz')
    cy.visit('http://localhost:3000')
      .get('form input').type('Denver')
      .get('.submit-button').click()
  })

  it('should display information for a single business', () => {
    cy.get('button').eq(8).click()
      .url('http://localhost:3000/shopping')
    cy.get('button')
      .should('contain', 'Learn More').eq(7).click()
    cy.url('http://localhost:3000/biz/dKf_zc_gvlQJRXXZNkUNng')
      .get('h2')
      .should('contain', 'Stanley Marketplace')
      .get('img')
      .should('have.attr', 'src')
      .url('https://s3-media1.fl.yelpcdn.com/bphoto/1qGXCCIqwJHV05leOS6yXw/o.jpg')
      .get('h3')
      .should('contain', 'Food Court')
      .and('contain', 'Location: 2501 Dallas St, Aurora, CO 80010')
      .and('contain', 'Hours:')
      .get('p')
      .should('contain', 'Monday: 7:00am - 9:00pm')
      .and('contain', 'Tuesday: 7:00am - 9:00pm')
      .and('contain', 'Wednesday: 7:00am - 9:00pm')
      .and('contain', 'Thursday: 7:00am - 10:00pm')
      .and('contain', 'Friday: 7:00am - 10:00pm')
      .and('contain', 'Saturday: 7:00am - 10:00pm')
      .and('contain', 'Sunday: 7:00am - 9:00pm')
      .get('h3')
      .should('contain', 'Contact:')
      .get('a')
      .should('contain', 'Visit Website')
      .should('have.attr', 'href')
      .url('https://www.yelp.com/biz/stanley-marketplace-aurora?adjust_creative=us0-GXhQzuMv9uLzOEXxpw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=us0-GXhQzuMv9uLzOEXxpw')
  })

  it('should change the url when viewing a business detail page', () => {
    cy.get('button').eq(8).click()
      .get('.listings-container button:first').click()
      .url('http://localhost:3000/biz/dKf_zc_gvlQJRXXZNkUNng')
  })

  it('should let you go back to the listings page from a single business view', () => {
    cy.get('button').eq(1).click()
      .url('http://localhost:3000/food')
    cy.get('button')
      .should('contain', 'Learn More').eq(9).click()
    cy.url('http://localhost:3000/biz/B2i4QJY03Iqo7gxdCnJbiw')
      .get('button')
      .should('contain', 'Go Back')
      .get('h2')
      .should('contain', 'Jamaican Grill')
      .get('button').eq(2).click()
    cy.url('http://localhost:3000/food')
  })

  it('should let you go back to the homepage from a single business view', () => {
    cy.get('button').eq(1).click()
      .url('http://localhost:3000/food')
    cy.get('button')
      .should('contain', 'Learn More').eq(9).click()
    cy.url('http://localhost:3000/biz/B2i4QJY03Iqo7gxdCnJbiw')
      .get('button')
      .should('contain', 'Go Back')
      .get('h2')
      .should('contain', 'Jamaican Grill')
      .get('button').eq(0).click()
      .url('http://localhost:3000')
  })
})
